Updated the Readme
kubernetes-sigs/contributor-katacoda pull request #3
Opened 2021-12-03 06:31 UTC by Debanitrkl

Updated the readme with basic information, will update more about how to use the katacoda scenario and more details guide on how to contribute to this after the integration is done and the first scenario is live on katacoda

2021-12-06 16:37 UTC, MadhavJivrajani reviewed
Thank you for seeding this!
Left a few comments :)
/cc @RinkiyaKeDad 
for feedback from a docs perspective. 

@Debanitrkl, if you haven't already, let's ask the marketing team for further feedback regarding the content and the phrasing/wording of things :)

2021-12-06 16:37 UTC, MadhavJivrajani commented on README.md
> +Welcome to Contribuotr Katacoda!
```suggestion
Welcome to Contributor Katacoda!
```

2021-12-06 16:37 UTC, MadhavJivrajani commented on README.md
> +This repository hosts katacoda scenarios for upstream contributors, it aims to help contributors starting up with upstream kubernetes to try their hand at making a patch and testing it.
```suggestion
This repository hosts Katacoda scenarios for aspiring contributors and aims to familiarize them with the process of contributing to Kubernetes.
```
Not sure if we're including testing of a custom patch made to the code base.
I think "upstream" here is implicit and need not be mentioned explicitly.

2021-12-06 16:37 UTC, MadhavJivrajani commented on README.md
> +Please feel free to join our [weekly meetings](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#mentoring) or reach out to the maintainers of this project.
I think this meeting is now cancelled and merged with the biweekly contribex meeting

2021-12-06 16:37 UTC, MadhavJivrajani commented on README.md
> +This repository will only host basic tutorials for upstream contributors, any end-user related tutorials/courses is out of the purview of this repsoiory and some of them are already hosted [here](htt
```suggestion
This repository will only host basic tutorials for contributors to familiarize themselves with the contribution process. Any end-user related tutorials/courses is out of the purview of this repository. End-user related scenarios may be found [here](https://www.katacoda.com/courses/kubernetes).
```

2021-12-06 16:50 UTC, RinkiyaKeDad requested changes

2021-12-06 16:50 UTC, RinkiyaKeDad commented on README.md
> +Welcome to Contribuotr Katacoda!
@Debanitrkl I would suggest putting the entire content in something like [Grammarly](https://www.grammarly.com/) once to easily catch all such errors :)

2021-12-06 16:50 UTC, RinkiyaKeDad commented on README.md
> +We are always looking for people to help us improve the katacoda scenario with more use cases. Look at our [contributing guide](CONTRIBUTING.md) to get started.
nit
```suggestion
We are always looking for people to help us improve these katacoda scenarios with more use cases. Look at our [contributing guide](CONTRIBUTING.md) to get started.
```

2021-12-06 16:50 UTC, RinkiyaKeDad commented on README.md
> +## Community, discussion, and support
Should we go with [Title Casing](https://titlecaseconverter.com/) for consistency?

```suggestion
## Community, Discussion, and Support
```

2021-12-06 16:50 UTC, RinkiyaKeDad commented on README.md
> +This repository will only host basic tutorials for upstream contributors, any end-user related tutorials/courses is out of the purview of this repsoiory and some of them are already hosted [here](htt
+1 to Madhav's suggestion and maybe also remove this line:

```
Any end-user related tutorials/courses is out of the purview of this repository.
```

Since the line after that conveys the same point.

2021-12-06 17:34 UTC, Debanitrkl commented on README.md
> +Please feel free to join our [weekly meetings](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#mentoring) or reach out to the maintainers of this project.
Just cancelled for this year, although I'm not sure yet about this

2021-12-06 17:39 UTC, Debanitrkl commented
Thanks, @MadhavJivrajani @RinkiyaKeDad for the reviews, I have updated the Readme accordingly

2021-12-06 17:41 UTC, jberkus requested changes
Please incorporate Madhav's changes.  Thanks!

2021-12-06 17:41 UTC, jberkus commented on README.md
> +This repository hosts katacoda scenarios for upstream contributors, it aims to help contributors starting up with upstream kubernetes to try their hand at making a patch and testing it.
Also "upstream" is not universally understood language.

2021-12-06 17:41 UTC, jberkus commented on README.md
> +Please feel free to join our [weekly meetings](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#mentoring) or reach out to the maintainers of this project.
We'll probably be resuming meetings in the new year, somehow.  Just not on the current schedule.

2021-12-06 17:41 UTC, jberkus commented on README.md
> +Please feel free to join our [weekly meetings](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#mentoring) or reach out to the maintainers of this project.
```suggestion
Please feel free to join our [weekly meetings](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#mentoring) or reach out to the maintainers of this project in the SIG-Contribex channel on [kubernetes slack](slack.k8s.io).
```

2021-12-06 17:43 UTC, Debanitrkl commented
> Please incorporate Madhav's changes. Thanks!

Done with this

2021-12-08 19:51 UTC, dims commented
/lgtm

2021-12-08 19:53 UTC, merged